[build-system]
requires = ["setuptools >= 78.1.0", "setuptools-rust >= 1.11.1"]
build-backend = "setuptools.build_meta"
[project]
name = "{{ cookiecutter.project_slug | replace('-', '_') }}"
version = "0.0.0"
authors = [
    { name = "{{ cookiecutter.project_author }}", email = "{{ cookiecutter.project_email }}" },
]
description = "{{ cookiecutter.project_description }}"
requires-python = ">={{ cookiecutter.project_python_version }}"
classifiers = [
    "Programming Language :: Python :: {{ cookiecutter.project_python_version }}",
    "Operating System :: OS Independent"
]
[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
[tool.setuptools.packages]
# Pure Python packages/modules
find = {}
[tool.ruff]
select = ["I"]
[[tool.setuptools-rust.ext-modules]]
# Private Rust extension module to be nested into the Python package
target = "{{ cookiecutter.project_slug | replace('-', '_') }}_rust._rust_functions" # The last part of the name (e.g. "_rust_functions", "_lib", etc) has to match lib.name in Cargo.toml, but you can add a prefix to nest it inside of a Python package
path = "{{ cookiecutter.project_slug | replace('-', '_') }}_rust/Cargo.toml"